apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: api-gateway
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: harbor.abcdavid.top/e_catalogue/gateway:0.0.113
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: GATEWAY_PORT
        - name: SERVER
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: GATEWAY_HOST
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_REFRESH_EXPIRES_IN
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_EXPIRES_IN
        
        - name: USERSMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_HOST
        - name: USERSMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_PORT

        - name: USERINFOMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERINFOMS_HOST
        - name: USERINFOMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERINFOMS_PORT

        - name: PRODUCTMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: PRODUCTMS_HOST
        - name: PRODUCTMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: PRODUCTMS_PORT

        - name: CONTACTMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: CONTACTMS_HOST
        - name: CONTACTMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: CONTACTMS_PORT

        - name: ORDERMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: ORDERMS_HOST
        - name: ORDERMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: ORDERMS_PORT
        
        - name: FILESERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: fileserver-config
              key: FILESERVER_HOST
        - name: FILESERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: fileserver-config
              key: FILESERVER_PORT
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: e-catalogue
spec:
  selector:
    app: api-gateway
  ports:
  - port: 3000
    targetPort: 3000

