apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: api-gateway
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: harbor.abcdavid.top/e_catalogue/gateway:0.0.61
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: GATEWAY_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secrets
              key: JWT_SECRET
        - name: JWT_REFRESH_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_REFRESH_EXPIRES_IN
        - name: JWT_EXPIRES_IN
          valueFrom:
            configMapKeyRef:
              name: jwt-config
              key: JWT_EXPIRES_IN
        - name: USERSMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_HOST
        - name: USERSMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_PORT
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: e-catalogue
spec:
  selector:
    app: api-gateway
  ports:
  - port: 3000
    targetPort: 3000

