apiVersion: v1
kind: ConfigMap
metadata:
  name: databases-config
  namespace: e-catalogue
  labels:
    app: e-catalogue
data:
  USERSDB_HOST: 'users-db'
  USERSDB_PORT: '3306'
  USERSDB_DATABASE: 'USERS'

  USERINFODB_HOST: 'userinfo-db'
  USERINFODB_PORT: '3306'
  USERINFODB_DATABASE: 'USERINFO'

  PRODUCTDB_HOST: 'product-db'
  PRODUCTDB_PORT: '3306'
  PRODUCTDB_DATABASE: 'PRODUCT'