apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: api-gateway
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: harbor.abcdavid.top/e_catalogue/gateway:0.0.29
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: api-gateway.port
        - name: USERSMS_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: users-ms.host
        - name: USERSMS_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: users-ms.healthcheck_port
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
