apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    labels:
      app: api-gateway
    name: api-gateway-ingress
    namespace: cicd-demo
  spec:
    ingressClassName: traefik
    rules:
    - host: cicd-demo.abcdavid.top
      http:
        paths:
        - backend:
            service:
              name: api-gateway
              port:
                number: 3000
          path: /
          pathType: Prefix
    tls:
    - hosts:
      - cicd-demo.abcdavid.top
      secretName: cicd-demo-tls
  status:
    loadBalancer: {}
kind: List
