apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-ms
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: order-ms
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: order-ms
    spec:
      containers:
      - name: order-ms
        image: harbor.abcdavid.top/e_catalogue/orderms:0.0.121
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: ORDERMS_PORT
        - name: HEALTHCHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: ORDERMS_HEALTHCHECK_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: ORDERDB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: ORDERDB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: ORDERDB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ORDERDB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ORDERDB_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: order-ms
  namespace: e-catalogue
spec:
  selector:
    app: order-ms
  ports:
  - port: 3000
    targetPort: 3000
