apiVersion: v1
kind: Service
metadata:
  name: order-db
  namespace: e-catalogue
spec:
  ports:
  - port: 3306
  selector:
    app: order-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: order-db
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-db
    spec:
      containers:
      - image: mysql:latest
        name: order-db
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: ORDERDB_DATABASE
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ORDERDB_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ORDERDB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: ORDERDB_PASSWORD
        ports:
        - containerPort: 3306
          name: order-db
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: order-db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: order-db-persistent-storage
        persistentVolumeClaim:
          claimName: order-db-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-db-pv-claim
  namespace: e-catalogue
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi