apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: users-ms
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
      - name: users-ms
        image: harbor.abcdavid.top/e_catalogue/usersms:0.0.29
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: users-ms.port
        - name: HEALTHCHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: users-ms.healthcheck_port
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
