apiVersion: v1
kind: Service
metadata:
  name: usersdb
  namespace: e-catalogue
spec:
  ports:
  - port: 3306
  selector:
    app: usersdb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersdb
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: usersdb
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: usersdb
    spec:
      containers:
      - image: mysql:latest
        name: usersdb
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: USERSDB_DATABASE
        # - name: MYSQL_ROOT_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: databases-secrets
        #       key: USERSDB_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: USERSDB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: USERSDB_PASSWORD
        ports:
        - containerPort: 3306
          name: usersdb
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        # volumeMounts:
        # - name: usersdb-persistent-storage
        #   mountPath: /var/lib/mysql
      # volumes:
      # - name: usersdb-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: usersdb-pv-claim
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: usersdb-pv-claim
#   namespace: e-catalogue
# spec:
#   storageClassName: longhorn
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi