apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-ms
  namespace: e-catalogue
spec:
  selector:
    matchLabels:
      app: users-ms
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: users-ms
    spec:
      containers:
      - name: users-ms
        image: harbor.abcdavid.top/e_catalogue/usersms:0.0.103
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_PORT
        - name: HEALTHCHECK_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-config
              key: USERSMS_HEALTHCHECK_PORT
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: USERSDB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: USERSDB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: databases-config
              key: USERSDB_DATABASE
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: USERSDB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: databases-secrets
              key: USERSDB_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: users-ms
  namespace: e-catalogue
spec:
  selector:
    app: users-ms
  ports:
  - port: 3000
    targetPort: 3000
